### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Starlinkboy** [moom825/Discord-RAT-2.0#10]
i ran it on a friend's computer. I also bypassed uac, got admin and added to startup. whenever they restart the laptop, it dosent star on startup

**Comment by Starlinkboy** [comment]
I think it works now....all it requires is the rootkit to be installed.
So if you want to add to startup...
Follow this:
1. !uacbypass
2. !rootkit
3. !startup
Should work hopefully

**Comment by moom825** [comment]
the rootkit should not make a difference, how strange...

**Comment by Starlinkboy** [comment]
It is weird. I dont really know C# so I couldn't fix. However I can share a recording of the bug if you wish.
Let me know which platform you prefer.

**Comment by moom825** [comment]
that would be great, feel free to dm me at `moom825#9999`
