### ISSUE TITLE
not working help

### ISSUE THREAD

**Issue by AstroSzefPL** [moom825/Discord-RAT-2.0#11]
after launching Client-built.exe discord bot dosent start and channels dont shows up

**Comment by supergarixd** [comment]
same happening here

**Comment by AstroSzefPL** [comment]
yes its very annoying im very frustated

**Comment by moom825** [comment]
i thought someone else would point out the problem, but i guess not. you have the wrong discord intents, you need to enable them all.

**Comment by Franklingdafoe** [comment]
Oh god damn, we are soo dumb haha

**Comment by Franklingdafoe** [comment]
Usually when you dont have the right intets the bot just doesn't see your messages so you cant use the commands but this time it did nothing so i had no idea on what to do.

**Comment by AstroSzefPL** [comment]
@Franklingdafoe i enabled them all bruh

**Comment by garix-png** [comment]
Did you enable administrator permissions in the OAuth2 section?
![image](https://user-images.githubusercontent.com/79505235/200376870-6d29f7f0-376c-4159-81aa-da6da53c19c2.png)

**Comment by garix-png** [comment]
if so can you send me a screenshot of the bot configuration?

**Comment by hoangdung1910** [comment]
Did you enable administrator permissions in the OAuth2 section?

**Comment by rohanraj-aipro** [comment]
> if so can you send me a screenshot of the bot configuration?

where to post the command and with what ?

**Comment by supergarixd** [comment]
what do you mean, can you specify wht command are you trying to use?

**Comment by rohanraj-aipro** [comment]
i'm just posting !screenshot in server. no response
