### ISSUE TITLE
Need some help w code / token

### ISSUE THREAD

**Issue by XcentricX** [moom825/Discord-RAT-2.0#12]
Hi moom, used your first RAT a while ago and really appreciate ur effort. Idk if ur willin for live discord help, but if not, I don't understand how I'm meant to 'open builder.exe' when the only builder file seems to be a csproj file. Any help?

**Comment by XcentricX** [comment]
prolly look rly stupid here but it's late and icba to try figure it out and mess it all up yk

**Comment by moom825** [comment]
try going to the releases tab, also my discord is `moom825#9999`
