### ISSUE TITLE
.

### ISSUE THREAD

**Issue by rikserok** [moom825/Discord-RAT-2.0#17]

**Comment by Blunerz** [comment]
update: i sent 1 command, it worked, but after this commands stopped working

**Comment by Blunerz** [comment]
i discoverded it works for 2-3 seconds

**Comment by moom825** [comment]
you might have the wrong message intents

**Comment by Blunerz** [comment]
![image](https://user-images.githubusercontent.com/105878986/201542985-f12e09d4-663f-4cf3-835c-79ce6cf83009.png)

**Comment by Blunerz** [comment]
idk what im doing wrong

**Comment by Blunerz** [comment]
can someone help

**Comment by RAZ321** [comment]
disable you antivirus

**Comment by Lilcapalotee** [comment]
exactly the same problem happening with me
