### ISSUE TITLE
you sure there is no backdoor that send you all info?

### ISSUE THREAD

**Issue by BlackDemonHat** [moom825/Discord-RAT-2.0#3]

**Comment by moom825** [comment]
are you goofy? its open source, read it (and no there is no backdoor)

**Comment by BlackDemonHat** [comment]
@moom825 idk c# thats why i am asking

**Comment by moom825** [comment]
well it is not backdoored, you can ask anyone who knows c# to look through the code if you dont trust me

**Comment by BlackDemonHat** [comment]
> well it is not backdoored, you can ask anyone who knows c# to look through the code if you dont trust me

@moom825 
ok and where i can add more commands XD i realy dont know c# just some c and python

**Comment by ch2sh** [comment]
asking the owner if it's backdoored as if they can't lie to you

**Comment by moom825** [comment]
you can legit look at the code 💀

**Comment by ch2sh** [comment]
> you can legit look at the code 💀

not accusing you of nothing man, just pointing out how inherently stupid this issue is to begin with

**Comment by moom825** [comment]
agreeable
