### ISSUE TITLE
startup doesent work.

### ISSUE THREAD

**Issue by ItsEnesN** [moom825/Discord-RAT-2.0#31]
The Startup doesent work.

**Comment by sefinek24** [comment]
Dont use this "rat", this "tool" is a fcking shit imo

**Comment by ItsEnesN** [comment]
which should i use?

**Comment by sefinek24** [comment]
You shouldn't :smile: :+1:

**Comment by sefinek24** [comment]
Or you can write message to his: https://flinek.ga
He is the best script kid in my country, master of python

but... important information
He doesn't understand english :kekw:

![yy8o7rgbxtp61](https://user-images.githubusercontent.com/92880265/212471170-82540964-2ce6-44a8-b5e2-37e9d19c1d05.jpg)

**Comment by ItsEnesN** [comment]
i just need a rat with a keylogger, basic stuff and it should be persistence.

**Comment by moom825** [comment]
well thats just rude, ngl.
