### ISSUE TITLE
Somehow getting other connections.

### ISSUE THREAD

**Issue by 3l41** [moom825/Discord-RAT-2.0#52]
After testing the rat on a vm and not spreading it at all. Not even taking it outside the vm, I am somehow getting connections to legitimate systems that I have not compromised my self.

**Comment by moom825** [comment]
well thats a +1 to another virustotal upload

**Comment by 3l41** [comment]
I am an idiot 🤦‍♂️

**Comment by 3l41** [comment]
Thanks for reminding me that I did that.
