### ISSUE TITLE
ok but how do you remove it

### ISSUE THREAD

**Issue by AverageVirusTotalEnjoyer** [moom825/Discord-RAT-2.0#57]
i pranked my friend but now hes pissed and i wanna remove it

**Comment by Hamza-Gits** [comment]
search it in the file explorer home page, search the file name and delete it there.

**Comment by A7QT** [comment]
!implode

**Comment by rohanraj-aipro** [comment]
Doesn't it have a self-erasing option?
A one single discord command, and the program self-destructs itself
