### ISSUE TITLE
tested it on myself and now im getting hacked

### ISSUE THREAD

**Issue by danny-125** [moom825/Discord-RAT-2.0#6]

**Comment by moom825** [comment]
what

**Comment by moom825** [comment]
can u provide a little more detail....

**Comment by danny-125** [comment]
like i ran it and now im getting random connections like george, abby, shit like that. kinda scaring me but i may have already been hacked.

**Comment by moom825** [comment]
you uploaded it to virustotal...dont do that.....

**Comment by danny-125** [comment]
oh thanks a lot, i thought i was getting hacked but i uploaded it to virus total because i wanted to see how bad it flagged.

**Comment by moom825** [comment]
what.....

**Comment by garix-png** [comment]
can you tell me the avs it falgged?

**Comment by jojo989** [comment]
what the actual fuck lmao
