### ISSUE TITLE
how do i know if this is a safe file. 

### ISSUE THREAD

**Issue by Hamza-Gits** [moom825/Discord-RAT-2.0#66]
My antivirus software's keep in coming up with the message that it is infected with trojan. How do i know this wont affect my computer?

**Comment by avighnac** [comment]
This is obviously a Trojan: this project is the definition of a Trojan (created for educational purposes). The difference here is that you're the attacker as well as the victim

**Comment by moom825** [comment]
just read the source code, theres a reason its there
