### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by RAZ321** [moom825/Discord-RAT-2.0#8]
Hey, this project is very cool and work, but i think it will be better if you add a feature that hide the .exe running from the taskmanager !

**Comment by moom825** [comment]
it already exists, check the options (ill give you a hint its call rootkit)

**Comment by ClaraCrazy** [comment]
*honk honk* 🤡

**Comment by RAZ321** [comment]
Oups! sorry i didn't see it.

**Comment by moom825** [comment]
you can use the change directory command....

**Comment by ClaraCrazy** [comment]
ong...
